### PR TITLE
Swift 4

### PR DESCRIPTION
**Pull request by danielsaidi**
Bug fixes for #172 and #173, as described here: https://github.com/AliSoftware/Dip/issues/173

### CODE REVIEW

**Comment by danielsaidi** [comment]
For the tests to work, Travis must run in Xcode 9 mode

**Comment by leandromperez** [comment]
Hey there! @ilyapuchka are you planning on releasing a new version that supports Swift 4?

**Comment by ilyapuchka** [comment]
yes, when GM will land

**Comment by ilyapuchka** [comment]
@danielsaidi I don't see any test failures or compiler errors on Xcode 9 GM, so I guess this change is not needed.

**Comment by ilyapuchka** [comment]
Ah, it was building with Swift 3.2 by default =(

**Comment by ilyapuchka** [comment]
@danielsaidi it still fails to compile on TypeForwardingTests.swift:156 and tests are failing in runtime.

**Comment by danielsaidi** [comment]
Hmmm...I use it in a project in Xcode 9b6 and it builds just fine and works great. I'm away for a couple of days, but I'll have a look at it once I'm back.



Skickat från min iPhone

**Comment by danielsaidi** [comment]
Hahaha I answered by replying from Gmail and it appended all that crap to the end. Can't edit it from my phone. Oh well 🙃

**Comment by ilyapuchka** [comment]
@danielsaidi thanks for your work! I used it in the #176

**Comment by ilyapuchka** [comment]
As soon as travis is back to normal I'll merge it and do a release

**Pull request closed without merging**
