### PR TITLE
Named first runtime argument in resolve

### LINKED ISSUE #18: Make first runtime argument parameter named
With introduction of runtime arguments (#8) the API became a bit confusing cause of mixing tags and arguments values. It would be better to use something like this: 

```swift
container.register(tag: "tag") { (arg1: Arg1) in ... as Protocol }
container.resolve(tag: "tag", withArguments: arg1) as Protocol
```

To release this feature faster and without bumping major version (what we are going to do to release circular dependencies) we can leave old version and later (or can we do it right away?) deprecate it.

### PR DESCRIPTION
**Pull request by ilyapuchka**
Resolves #18

### CODE REVIEW

**Comment by AliSoftware** [comment]
This means a 3.1.0 before the 4.0.0, right?

**Comment by ilyapuchka** [comment]
I don't mind bumping major version and release it together with other things that are in develop now. To release 3.1 first will be too much updates in short time. But do you think it will be ok just to remove old methods without deprecating them first? Currently in develop `register(instance)` is only deprecated. Then we can remove them all together in 4.1?

P.S. probably I don't have access rights to create milestones and labels...

**Comment by AliSoftware** [comment]
I think removing without deprecating might be maybe harsh but not _that_ problematic either, as long as we provide a clear note in the CHANGELOG.

We can't deprecate in 4.0.x and remove in 4.1.x because that would break [semantic versioning](http://semver.org): when you remove a method and thus break the backward compatibility you have to bump the major version. So the solutions to chose from are:

* deprecate it in 3.1 and remove in 4.0
* deprecate in 4.0 and remove in 5.0
* remove in 4.0 without deprecating it before

I think the first one would be the best, because typically when you do semver you use `~> 3.0` — so a `pod update` will update to 3.1 but not 4 until you change your Podfile manually. But if we dont plan to release a 3.1, then the last one won't be as problematic as if we were Apple or a big lib IMHO. After all we only have 50 stars so far, not 1k :wink:

**Comment by ilyapuchka** [comment]
Ok, I see. But then if we deprecate it in 3.1 then we need to provide an alternative in the same version, don't we? For named arguments we have it, but for registering singleton we need to extract it from circular dependencies implementation. If it's ok I can do that.

**Comment by AliSoftware** [comment]
Indeed, I didn't realize that the alternative for `register(instance:)` was only provided by the Circular Dependencies PR. To follow semver and be nice citizen with the API changes we should indeed extract the alternate `register(.Singleton)` from there so it can be included in 3.1 before we release Circular Dependencies in 4.0.

**Comment by ilyapuchka** [comment]
Ok, let's do that. I think it will be easier to start `release/3.1.0` brunch from current master and do it there (we can't start it from develop cause circular dependencies are already merged in). And we need to close this then two.

**Comment by AliSoftware** [comment]
Yeah we messed up a bit with te branches this time, it wasn't proper gitflow as we didn't have the roadmap yet, woops.

We can still create the branch from develop, but from an earlier commit in develop before we merged circular dependencies PR (and cherry-pick the missing, more recent commits from develop into release/3.1.0 if needs be). I think it would feel better than starting a release from master.

**Comment by ilyapuchka** [comment]
Ok, will do that tomorrow.

**Comment by AliSoftware** [comment]
Well I just took a look at the git graph and realize that… I already did exactly that 4 days ago :smile: 

Branch `origin/release/3.1.0` [was created 4 days ago](https://github.com/AliSoftware/Dip/branches) and points the the commit just after the release 3.0.0 and just before the Circular Dependencies branches started :wink:

**Comment by ilyapuchka** [comment]
So can we close that?

**Comment by ilyapuchka** [comment]
Maybe it will also worth adding `inScope` name to scope parameter in `register`? It can be also confusing if you use it together with tag: 
`register(tag: "tag", .Singleton) { ... }` vs `register(tag: "tag", inScope: .Singleton) { ... }` or `register(inScope: .Singleton) { ... }`

**Comment by AliSoftware** [comment]
Mmh given that the Scope is a fixed enum, I'm not sure the confusion can be done like there was the confusion between tag and runtime argument before?

**Comment by ilyapuchka** [comment]
Yep, let's leave it like it is.
So I've made a pull request for 3.1.0 release - https://github.com/AliSoftware/Dip/pull/21

**Comment by AliSoftware** [comment]
Cool! Will close this issue once I took time to merge #21 :)

**Comment by ilyapuchka** [comment]
We now don't need this as it is now in develop after merge of release/3.1.0 - 97782364167a1d8504d730922f31176ab3683229

**Pull request closed without merging**
