### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by ilyapuchka**
https://github.com/AliSoftware/Dip/wiki/Roadmap#version-310

### CODE REVIEW

**Comment by AliSoftware** [comment]
Great, will look at that this week-end!

**Comment by AliSoftware** [comment]
Ok, so,

I'm ok with the content of that release/3.1.0 branch and ready to merge.

But I tried finishing the release and got conflicts when gitflow is trying to merge the `release` into `develop`, and I have to admit I'm not totally confident with resolving those conflicts. Especially when merging `release/3.1.0` into `develop` some lines came from `3.1.0` and others from changes made during the `feature/circular-dependency` feature branch.

Besides I realized that when you made your `hotfix/migration-note` branch I merged it via GitHub so it only merged it into `master` and didn't treat it as a proper git-flow hotfix, where it should also have been merged into `develop` too; so we had that commit missing in `develop` too now, and the git graph starts to be a bit messy..

## Here's what I did so far

1. I merged the `hotfix/migration-note` commit into `develop`, like it should have been done all along if I didn't merge the PR via GitHub but via a proper git-flow process, sorry for that
2. I rebased `feature/auto-injection` and `feature/named-runtimer-arguments` on top of that new `develop`

## Here's what remains to do

1. git-flow finish release the `release/3.1.0` branch, meaning that we need to merge it into `master` (no problem here) and into `develop` (leading to conflicts i'm not confident enough to resolve, fearing it might break your work on develop)
2. Maybe rebase the `feature/*` branches on top of develop once that merge is done to have a cleaner and more understandable git graph from now on?
3. Check everything, as this Git graph is looking a bit like spaghettis lately so a mistake can quickly slip through. Especially check that the code in master after the 3.1.0  tag is indeed what we expect it to be and we didn't mess up the merge in the process, and that develop didn't get any regression during the merge/rebease either

**Comment by ilyapuchka** [comment]
No problem, I will do the merge. Will close this then and make a release.

**Comment by AliSoftware** [comment]
I realize that you may not have the access right to merge to master but at least you should be able to merge to develop then I can merge to master myself.

**Comment by ilyapuchka** [comment]
Ok. So I'm pushed develop with this brunch merged in :tada: 
Feel free to close this and make a release.

**Comment by AliSoftware** [comment]
> with this brunch

:egg: :smile: 

Talking about brunch, will close and release that after lunch :wink:

**Comment by AliSoftware** [comment]
Version 3.1.0 released and pushed to CocoaPods ! :tada: Thanks for your work on this!

You can now rebase the `feature/auto-injecton` branch on top of `develop`, and remove the `feature/named-runtime-arguments` branch.

**Pull request merged**
